# Generated by Django 4.2.4 on 2025-08-04 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creche', '0001_initial'),
        ('status', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtCadastro', models.DateTimeField(default=datetime.datetime.now, verbose_name='Dt.Cadastro')),
                ('dtAtendimento', models.DateField(blank=True, null=True, verbose_name='Dt.Atendimento')),
                ('observacao', models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.candidato')),
                ('modalidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creche.modalidade')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.status')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='creche.unidade')),
                ('unidadeAtend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidade_atend', to='creche.unidade')),
            ],
            options={
                'unique_together': {('unidade', 'modalidade', 'candidato')},
            },
        ),
    ]
