# Generated by Django 4.2.4 on 2025-08-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('faixaEtaria', models.CharField(blank=True, max_length=150, null=True, verbose_name='Faixa Etária')),
            ],
            options={
                'verbose_name': 'modalidade',
                'verbose_name_plural': 'modalidades',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'tipo de unidade',
                'verbose_name_plural': 'tipo de unidades',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.endereco')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='UnidadeModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creche.modalidade')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creche.unidade')),
            ],
            options={
                'verbose_name': 'modalidade',
                'verbose_name_plural': 'modalidades',
                'unique_together': {('unidade', 'modalidade')},
            },
        ),
        migrations.AddField(
            model_name='unidade',
            name='modalidades',
            field=models.ManyToManyField(through='creche.UnidadeModalidade', to='creche.modalidade'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='tipoUnidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creche.tipounidade', verbose_name='Tp.Unidade'),
        ),
    ]
