# Generated by Django 4.2.4 on 2025-08-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidademodalidade',
            options={},
        ),
    ]
