# Generated by Django 4.2.4 on 2025-08-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'bairro',
                'verbose_name_plural': 'bairros',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.bairro')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('documento', models.CharField(max_length=250, null=True, verbose_name='Documento')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.endereco')),
            ],
            options={
                'verbose_name': 'responsável',
                'verbose_name_plural': 'responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(verbose_name='DDD')),
                ('numero', models.CharField(max_length=250, verbose_name='Número')),
                ('whatsapp', models.BooleanField(null=True, verbose_name='Whatsapp?')),
                ('telegram', models.BooleanField(null=True, verbose_name='Telegram?')),
                ('email', models.EmailField(max_length=250, null=True, verbose_name='E-mail')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos', to='cadastro.responsavel')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('dtNascimento', models.DateField(verbose_name='Dt.Nascimento')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.endereco')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.responsavel')),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidatos',
            },
        ),
    ]
